### ISSUE TITLE
Test issue creation.

### ISSUE THREAD

**Issue by Traap** [Traap/dotfiles-archived#12]
## Todo List
- [x] Get company name and address
- [x] What is the requisition number? 498239
- [x] Is this a medical device position?
- [x] Update jobs.csv
- [x] Update jobnbr.tex
- [x] Assemble cover letter
- [x] Compile resume
- [x] Apply on company website

**Comment by Traap** [comment]
This issue was used to test jaxbot/github-issues.vim and nothing else.

**Comment by Traap** [comment]
Git-commit 6241908 completed this task.
